language: node.js
node_js:
  - '10'
script:
  - docker build -t jtwebman/node-express-docker-starter:dev --target=development .
  - docker build -t jtwebman/node-express-docker-starter .
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
